data_loader:
  name: "CIFAR10"
  augmentations: [[]] 
  input_shape: [3, 32, 32]
  hdf5: ["clean.hdf5"]
test:
  method: "rank_pruning"
  model: "resnet18"
  num_classes: 10
  device: "cuda:0"
  models_names: ["cifar_clean"]
  models_paths: ["models/cifar_clean_aug/checkpoint_198.tar"]
  true_delta_matrices: [
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 1, 0, 0., 0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0., 0., 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
                 ]



