data_loader:
  name: "CIFAR10"
  augmentations: ["rot"]
  input_shape: [3, 32, 32]
  delta_matrix: [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.8, 0.1, 0.1, 0., 0., 0., 0., 0., 0.],
                 [0, 0.1, 0.8, 0.1, 0., 0, 0., 0., 0., 0.],
                 [0., 0.1, 0.1, 0.8, 0., 0, 0., 0, 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 70
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/rot/cifar_swap3"
  save_as: "rot/cifar_swap3"
  num_classes: 10
  resume: False 
