data_loader:
  name: "CIFAR10"
  augmentations: [[], ["rot_1"], ["rot_2"], ["rot_4"], ["rot_8"], ["rot_16"]]
  input_shape: [3, 32, 32]
test:
  model: "resnet18"
  num_classes: 10
  device: "cuda:0"
  models_names: ["cifar_clean", "cifar_swap2", "cifar_swap3", "cifar_swap5"]
  models_paths: ["models/rot/cifar_clean/checkpoint_44.tar", "models/rot/cifar_swap2/checkpoint_44.tar", "models/rot/cifar_swap3/checkpoint_44.tar", "models/rot/cifar_swap5/checkpoint_44.tar"]
  true_delta_matrices: [
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 1, 0, 0., 0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0., 0., 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.4, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0.4, 0.6, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.2, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0, 0.2, 0.6, 0.2, 0., 0, 0., 0., 0., 0.],
                 [0., 0.2, 0.2, 0.6, 0., 0, 0., 0, 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[0.6, 0.1, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.6, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.6, 0.1, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.6, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.1, 0.6, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
]




