data_loader:
  name: "CIFAR10"
  augmentations: [[], ["rot_1"], ["rot_2"], ["rot_3"], ["rot_4"], ["rot_5"], ["rot_6"], ["rot_7"], ["rot_8"], ["rot_9"], ["rot_10"]]
  input_shape: [3, 32, 32]
  hdf5: "cifar_clean_rot.hdf5"
test:
  model: "resnet18"
  num_classes: 10
  device: "cuda:0"
  models_names: ["cifar_clean"]
  models_paths: ["models/rot/cifar_clean/checkpoint_60.tar"]
  true_delta_matrices: [
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 1, 0, 0., 0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0., 0., 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
                 ]



