data_loader:
  name: "CIFAR10"
  augmentations: ["hflip", "five_crop", "rot"]
  input_shape: [3, 32, 32]
  delta_matrix: [[0.6, 0.1, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.6, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.6, 0.1, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.6, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.1, 0.6, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  method: "TTA"
  device: "cuda:2"
  num_epochs: 150
  model: "resnet18"
  learning_rate: 0.1
  save_dir: "models/cifar_swap5"
  save_as: "cifar_swap5"
  num_classes: 10
  resume: False
