data_loader:
  name: "CIFAR10"
  augmentations: ["hflip", "five_crop"]
  input_shape: [3, 32, 32]
  delta_matrix: [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0, 0.4, 0., 0., 0., 0., 0., 0.],
                 [0, 0, 0.6, 0, 0., 0.4, 0., 0., 0., 0.],
                 [0., 0, 0, 0.6, 0., 0, 0., 0.4, 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0. 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/cifar_swap3"
  save_as: "cifar_swap3"
  num_classes: 10
  resume: False 
