data_loader:
  name: "CIFAR10"
  augmentations: ["hflip", "five_crop"]
  input_shape: [3, 32, 32]
test:
  model: "resnet18"
  num_classes: 10
  device: "cuda:0"
  models_names: ["cifar_2class/0.9_0.1", "cifar_2class/0.8_0.2", "cifar_2class/0.7_0.3", "cifar_2class/0.6_0.4"]
  models_paths: ["models/cifar_2class/0.9_0.1/checkpoint_44.tar", "models/cifar_2class/0.8_0.2/checkpoint_44.tar", "models/cifar_2class/0.7_0.3/checkpoint_44.tar", "models/cifar_2class/0.6_0.4/checkpoint_44.tar"]
  true_delta_matrices: [[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.9, 0.1, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.8, 0.2, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.7, 0.3, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.4, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]

]




