data_loader:
  name: "CIFAR10"
  augmentations: [["five_crop", "hflip"]]
  input_shape: [3, 32, 32]
  hdf5: ["cifar_swap2.hdf5", "cifar_swap3.hdf5", "cifar_swap5.hdf5"]
test:
  method: "TTA"
  model: "resnet18"
  num_classes: 10
  device: "cuda:2"
  models_names: ["cifar_swap2", "cifar_swap3", "cifar_swap5"]
  models_paths: ["models/cifar_swap2/checkpoint_248.tar", "models/cifar_swap3/checkpoint_110.tar" , "models/cifar_swap5/checkpoint_98.tar"]
  true_delta_matrices: [
          #[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
          #                 [0., 1, 0, 0., 0., 0., 0., 0., 0., 0.],
          #       [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
          #       [0., 0., 0., 1, 0., 0, 0., 0., 0., 0.],
          #       [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
          #       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
          #       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
          #       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
          #       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
          #       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.4, 0,  0., 0., 0., 0., 0., 0.],
                 [0, 0.4, 0.6, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0 , 0, 1, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0, 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.2, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0, 0.2, 0.6, 0.2, 0., 0, 0., 0., 0., 0.],
                 [0., 0.2, 0.2, 0.6, 0., 0, 0., 0, 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
[[0.6, 0.1, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.6, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.6, 0.1, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.6, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.1, 0.6, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
]




