data_loader:
  name: "CIFAR10"
  delta_matrix: [[0.9, 0.1, 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0.9, 0.1, 0., 0., 0., 0., 0., 0., 0.],
       [0.1, 0., 0.9, 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0.9, 0., 0.1, 0., 0., 0., 0.],
       [0., 0., 0.1, 0., 0.9, 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "LogisticRegression"
  learning_rate: 0.001
  save_dir: "models/cifar10"
  save_as: "cifar10"
  num_classes: 10
  resume: False 
