train:
    n_examples: 10000
    class_split: [0.5, 0.5]
    n_runs: 5 
    n_classes: 2
    distribution:
        class_0:
            name: "exponential"
            parameters:
                scale: 1
                mean: 0.5
        class_1:
           name: "exponential"
           parameters:
               scale: 1.5
experiment:
    class_noise_difference:
        delta_stars: [0.1, 0.2, 0.3, 0.4, 0.5]
    fixed_total_noise:
        noise: [0.2, 0.4, 0.6, 0.8]
    fix_delta0_vary_delta1:
        delta0_range: [0.1, 0.4]
        delta1_range: [0.1, 0.9]
plots:
    delta_matrix: [[0.8, 0.2], [0.3, 0.7]] 
