data_loader:
  name: "MNIST"
  delta_matrix: [[0.6, 0.1, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.6, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.6, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.6, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.1, 0.6, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0. 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/mnist_swap5"
  save_as: "mnist_swap5"
  num_classes: 10
  num_channels: 1
  resume: False 
