data_loader:
  name: "MNIST"
  delta_matrix: [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.8, 0, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.2 , 0, 0.8, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0. 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/mnist_swap2"
  save_as: "mnist_swap2"
  num_classes: 10
  num_channels: 1
  resume: False 
