data_loader:
  name: "MNIST"
  augmentations: ["hflip", "five_crop"]
  input_shape: [1, 28, 28]
  delta_matrix: [[0.6, 0, 0.2, 0, 0.2, 0., 0., 0., 0., 0.],
                 [0, 0.6, 0.3, 0, 0.1, 0., 0., 0., 0., 0.],
                 [0, 0.2, 0.6, 0, 0, 0.2, 0., 0., 0., 0.],
                 [0.3, 0, 0.7, 0, 0, 0, 0., 0., 0., 0.],
                 [0, 0, 0.2, 0, 0.8, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0. 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/mnist_swap5sep_aug"
  save_as: "mnist_swap5sep_aug"
  num_classes: 10
  num_channels: 1
  resume: False 
