data_loader:
  name: "MNIST"
  augmentations: ["five_crop"]
test:
  model: "resnet18"
  num_classes: 10
  num_channels: 1
  device: "cuda:0"
  models_names: ["mnist_swap2", "mnist_swap3", "mnist_swap5"]
  models_paths: ["models/mnist_swap2sep_aug/checkpoint_19.tar", "models/mnist_swap3sep_aug/checkpoint_19.tar", "models/mnist_swap5sep_aug/checkpoint_19.tar"]
  true_delta_matrices: [
 [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.8, 0, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0, 0., 1, 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.2 , 0, 0.8, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
 [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0.2, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0, 0.2, 0.6, 0.2, 0., 0., 0., 0., 0., 0.],
                 [0., 0.2, 0.2, 0.6, 0., 0, 0., 0., 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]],
 [[0.6, 0.1, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.6, 0.1, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.6, 0.1, 0.1, 0., 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.6, 0.1, 0, 0., 0., 0., 0.],
                 [0.1, 0.1, 0.1, 0.1, 0.6, 0, 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]]



