data_loader:
  name: "MNIST"
  augmentations: ["hflip", "five_crop"]
  input_shape: [1, 28, 28]
  delta_matrix: [[1, 0, 0., 0., 0., 0., 0., 0., 0., 0.],
                 [0., 0.6, 0, 0.4, 0., 0., 0., 0., 0., 0.],
                 [0, 0, 0.6, 0, 0., 0.4, 0., 0., 0., 0.],
                 [0., 0, 0, 0.6, 0., 0, 0., 0.4, 0., 0.],
                 [0., 0., 0, 0., 1,  0., 0., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 1., 0., 0., 0. 0.],
                 [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
                 [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]
train:
  device: "cuda:0"
  num_epochs: 20
  model: "resnet18"
  learning_rate: 0.005
  save_dir: "models/mnist_swap3sep_aug"
  save_as: "mnist_swap3sep_aug"
  num_classes: 10
  num_channels: 1
  resume: False 
