train:
    n_classes: 4
    n_examples: 10000
    class_split: [0.25, 0.25, 0.25, 0.25]
    n_runs: 10
    distribution:
        class_0:
            name: "gaussian"
            parameters:
                mean: [0, 1]
                cov: [[2, 0], [0, 2]]
        class_1:
            name: "gaussian"
            parameters:
                mean: [1, 0]
                cov: [[2, 0], [0, 2]]
        class_2:
            name: "gaussian"
            parameters:
                mean: [0, -1]
                cov: [[2, 0], [0, 1]]
        class_3:
            name: "gaussian"
            parameters:
                mean: [-1, 0]
                cov: [[1, 0], [0, 2]]
experiment:
    multiclass_simple: True
#        delta_0: 0.3
#        delta_1: 0.6
    multiclass_advanced:
#        deltas: [0.3, 0.3, 0, 0]
plots:
    delta_matrix: [[1, 0, 0, 0], [0.1, 0.7, 0.1, 0.1], [0, 0, 1, 0], [0, 0, 0, 1]]
